//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDB.HPApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDB.HPApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Briv&quot;,
        ///  &quot;level&quot;: 5,
        ///  &quot;hitPoints&quot;: 25,
        ///  &quot;classes&quot;: [
        ///    {
        ///    &quot;name&quot;:&quot;fighter&quot;,
        ///    &quot;hitDiceValue&quot;:10,
        ///    &quot;classLevel&quot;:5
        ///    }
        ///  ],
        ///  &quot;stats&quot;:{
        ///    &quot;strength&quot;:15,
        ///    &quot;dexterity&quot;:12,
        ///    &quot;constitution&quot;:14,
        ///    &quot;intelligence&quot;:13,
        ///    &quot;wisdom&quot;:10,
        ///    &quot;charisma&quot;:8
        ///  },
        ///  &quot;items&quot;:[
        ///    {
        ///      &quot;name&quot;:&quot;Ioun Stone of Fortitude&quot;,
        ///      &quot;modifier&quot;:{
        ///        &quot;affectedObject&quot;:&quot;stats&quot;,
        ///        &quot;affectedValue&quot;:&quot;constitution&quot;,
        ///        &quot;value&quot;:2
        ///      }
        ///    }
        ///  ],
        ///  &quot;defense [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string briv {
            get {
                return ResourceManager.GetString("briv", resourceCulture);
            }
        }
    }
}
